# Generated by Django 6.0.2 on 2026-05-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=25)),
                ('File', models.FileField(max_length=254, upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDF', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Area',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
