# Generated by Django 4.2.29 on 2026-05-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0004_filemodel_pdf_alter_teacher_area_alter_teacher_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit', models.CharField(blank=True, max_length=25)),
                ('Task', models.CharField(blank=True, max_length=25)),
                ('DueDate', models.CharField(blank=True, max_length=25)),
                ('Weight', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='filemodel',
            name='Title',
        ),
        migrations.AddField(
            model_name='filemodel',
            name='AditionalInfo',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='Class',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='Description',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='Unit',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='File',
            field=models.FileField(blank=True, upload_to='H:/Programming/Calvin/Calvin/MyApp1/files'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='twin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
