# Generated by Django 4.2.29 on 2026-05-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0005_assessment_remove_filemodel_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(blank=True, max_length=25)),
                ('Unit', models.CharField(blank=True, max_length=25)),
                ('Description', models.CharField(blank=True, max_length=25)),
                ('AdditionalInfo', models.FileField(blank=True, upload_to='C:/Users/LiamA/source/repos/Liam-Angel/Calvin/Calvin/MyApp1/files/')),
            ],
        ),
        migrations.DeleteModel(
            name='fileModel',
        ),
        migrations.RenameModel(
            old_name='assessment',
            new_name='tasks',
        ),
        migrations.AddField(
            model_name='units',
            name='Assessment',
            field=models.ManyToManyField(to='MyApp1.tasks'),
        ),
    ]
